# shellcheck shell=bash

if patched_font_in_use; then
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD=""
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN=""
else
	TMUX_POWERLINE_SEPARATOR_LEFT_BOLD="◀"
	TMUX_POWERLINE_SEPARATOR_LEFT_THIN="❮"
	TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD="▶"
	TMUX_POWERLINE_SEPARATOR_RIGHT_THIN="❯"
fi

# Main colors (Hacker purple + neon glow style)
TMUX_POWERLINE_DEFAULT_BACKGROUND_COLOR="235"     # Dark gray background
TMUX_POWERLINE_DEFAULT_FOREGROUND_COLOR="201"     # Neon magenta text

# Default separators
TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR=$TMUX_POWERLINE_SEPARATOR_RIGHT_BOLD
TMUX_POWERLINE_DEFAULT_RIGHTSIDE_SEPARATOR=$TMUX_POWERLINE_SEPARATOR_LEFT_BOLD

# Window styles
if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_CURRENT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_CURRENT=(
		"#[$(format inverse)]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
		" #I#F "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
		"#[$(format regular)]"
		"$TMUX_POWERLINE_DEFAULT_LEFTSIDE_SEPARATOR"
	)
fi

if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_STYLE" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_STYLE=(
		"$(format regular)"
	)
fi

if [ -z "$TMUX_POWERLINE_WINDOW_STATUS_FORMAT" ]; then
	TMUX_POWERLINE_WINDOW_STATUS_FORMAT=(
		"#[$(format regular)]"
		"  #I#{?window_flags,#F, } "
		"$TMUX_POWERLINE_SEPARATOR_RIGHT_THIN"
		" #W "
	)
fi

# LEFT segments (purple / neon)
TMUX_POWERLINE_LEFT_STATUS_SEGMENTS=(
	"tmux_session_info 93 235"
	"hostname 93 0"
	"lan_ip 93 0 ${TMUX_POWERLINE_SEPARATOR_RIGHT_THIN}"
	"wan_ip 93 0"
	"vcs_branch 165 0"
)

# RIGHT segments (neon contrast)
TMUX_POWERLINE_RIGHT_STATUS_SEGMENTS=(
	"pwd 93 235"
	"load 237 165"
	"battery 93 235"
	"date_day 235 165"
	"date 235 165 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
	"time 235 165 ${TMUX_POWERLINE_SEPARATOR_LEFT_THIN}"
)

